language: node_js
node_js:
  - 14
script:
  - yarn lint
  - yarn build
cache: yarn
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build
  on:
    branch: master
  github_token: $GITHUB_TOKEN
